feat(print-version): add print-version command to output version
relekang/python-semantic-release pull request #309
Opened 2021-01-06 15:25 UTC by Toilal

This new command can be integrated in the build process before the effective release, ie. to rename some files with the version number.

Users may invoke `VERSION=$(semantic-release print-version)` to retrieve the version that will be generated during the release before it really occurs.

2021-01-06 15:38 UTC, Toilal commented
In fact, most users won't need this. 

But in my use case (related to PR #308), the build is not performed by semantic-release but by some github actions running in another job. So I need to retrieve the version number that semantic-release will generate to rename the artifacts generated by github actions, before placing them in the dist directory and running the `semantic-release publish` command.

2021-01-07 14:53 UTC, relekang requested changes

2021-01-07 14:53 UTC, relekang commented on semantic_release/cli.py
> +@main.command(name="print-version", help=version.__doc__)
```suggestion
@main.command(name="print-version", help=print_version.__doc__)
```

2021-01-07 14:54 UTC, relekang commented
Nice, just added one suggestion since it seems to be a copy-paste error?

2021-01-07 19:40 UTC, Toilal commented on semantic_release/cli.py
> +@main.command(name="print-version", help=version.__doc__)
Oops :) It's fixed now, thanks.

2021-01-08 07:42 UTC, relekang commented
Just realised that changing the location of the main will break the github action. Can you please update https://github.com/relekang/python-semantic-release/blob/master/action.sh#L17 to work with the new setup?

2021-01-08 08:59 UTC, Toilal commented
good catch, I just fixed this one, thanks.

2021-01-08 11:02 UTC, merged