Allow using ssh-key to push version while using token to publish to hvcs
relekang/python-semantic-release pull request #419
Opened 2022-02-22 17:26 UTC by sp-ricard-valverde

# Scenario

In GH Actions I want to use a ssh Deploy Key to push changes to a _protected_ branch because not every user's GITHUB_TOKEN is allowed to push to _protected_ branches but Deploy Keys are.

# Problematic

If I specify a `GH_TOKEN` such as `GITHUB_TOKEN` in a GitHub Action with enough permission to publish a GitHub Release, python-semantic-releases will also use that user's token to push version and tag changes to the repository.
The user running the action though might not have enough permission to push to a _protected_ branch even if grating some degree of permission to its `GITHUB_TOKEN`. Only Deploy Keys or Admin user's `GITHUB_TOKEN`(or Personal Access Tokens) can.

# Solution

Add an option that will allow to use the token to submit GitHub Releases while will avoid using that token for pushing changes to the repository, relying on the underlying git authentication mechanism. In the case of GitHub Actions it can be combined with [ssh-agent action](https://github.com/webfactory/ssh-agent) to allow using Deploy Keys for this purpose.

2022-04-01 15:50 UTC, sp-ricard-valverde commented
Anyone ?

2022-04-03 11:33 UTC, danth requested changes
Please add the new option to the documentation in `docs/configuration.rst`.

Other than that, this looks good to me.

2022-04-13 18:07 UTC, danth approved these changes

2022-04-13 18:08 UTC, danth commented
Looks like some tests need to be fixed.

2022-04-14 12:26 UTC, sp-ricard-valverde commented
I'll look into it, thanks @danth

2022-05-25 10:40 UTC, sp-ricard-valverde commented
Sorry for the late fix @danth. I've figured out the problem which had to do with the GITHUB_ACTOR env var set by the GH runners altering the test outcome(thus why locally the tests were ok)

2022-05-25 13:49 UTC, danth commented
One of the tests is still broken 🤔 Perhaps there is still some interference from the test environment.

2022-05-25 17:06 UTC, sp-ricard-valverde commented
Hope this one works. I explicitly added the GITHUB_ACTOR env var to my test execution to emulate the runner behaviour

2022-05-25 17:14 UTC, merged