fix(prerelase): pass prerelease option to get_current_version
relekang/python-semantic-release pull request #432
Opened 2022-03-30 08:17 UTC by anehx

The `get_current_version` function accepts a `prerelease` argument which was never passed.

2022-03-30 08:22 UTC, anehx commented
The test for this never failed because it was mocked correctly: 

https://github.com/relekang/python-semantic-release/blob/85158798ca438c1dafc84036d13c2988c934f02f/tests/test_cli.py#L357-L359

However, `get_current_version` could never have returned this value because the `prerelease_bool` argument was never passed which lead to ignoring **all** prereleases:

https://github.com/relekang/python-semantic-release/blob/85158798ca438c1dafc84036d13c2988c934f02f/semantic_release/history/__init__.py#L230

2022-03-30 16:29 UTC, danth requested changes
Please fix the failing tests.

2022-03-31 11:38 UTC, anehx commented
@danth the tests should pass now..

2022-04-03 11:30 UTC, danth approved these changes

2022-04-03 11:31 UTC, merged