fix: get_current_release_version incorrectly parses commit message with version
relekang/python-semantic-release pull request #444
Opened 2022-05-06 05:04 UTC by ngshiheng

**Context:**
- Related to https://github.com/relekang/python-semantic-release/issues/442
- The most recent PR that was merged https://github.com/relekang/python-semantic-release/pull/435 seems to be causing this issue
- From my observation and tests, `get_current_release_version_by_commits` seems to be parsing version incorrectly from commit messages
- For example, this issue occurs when the commit messages that contain versioning, e.g. "fix(deps): update dependency pylint to 2.13.8" are parsed

**Main changes:**
- `get_commit_log` now yields an additional `commit.author` info to the current tuple returned
- `get_current_release_version_by_commits` now checks that `commit_author.name == "github-actions" and commit_author.email == "action@github.com"` before returning version that matches regex in the commit message

**Description:**
- The main idea behind this change is that there is not really a sure-fire way for us to parse versions correctly from users' commit messages as users can write commit messages however they want
- This fix checks for the commit author to cope with the issue above

Let me know if this works.

2022-05-06 15:35 UTC, ngshiheng commented
I'm not sure why mypy failed here, any ideas?

2022-05-08 17:39 UTC, danth requested changes
When Python semantic release is not running under GitHub Actions, the commit author will be different. I don't see any obvious way of knowing what the author will be in these cases.

https://github.com/relekang/python-semantic-release/blob/94c94942561f85f48433c95fd3467e03e0893ab4/action.sh#L15-L17

We could parse the local Git configuration, however, some people might be using their own account details for Python semantic release commits. It's also possible for the commit author to be changed at any point in the project's history.

Currently, these changes will stop versions from being detectable in a non-Actions setting.

2022-05-09 08:50 UTC, jacksbox commented
first: sorry for introducing this issue. I wrote about this issue in context of the change-log here already https://github.com/relekang/python-semantic-release/issues/424 but somehow missed to to think about it in terms of the prerelease implementation. 

I see two options for quick solutions: 
1. rollback the prerelease changes until we have a better solution
2. add an unchangeable identifier to the commit message, e.g. always let the commit subject end with `@python-semantic-release` and use this to verify that we have the correct commit...

For the future, let's discuss here https://github.com/relekang/python-semantic-release/issues/424 if perhaps having only tags as version sources could make this package more robust and make changes / addons easier....

2022-05-09 09:39 UTC, ngshiheng commented
@danth makes sense. I didn't consider the fact that users could be using python-semantic-release without GitHub Actions. this PR won't work then. i'll go ahead and close this PR

@jacksbox no worries! i'd go with quick solution 1 as i'd expect this bug to break lots of repositories' CI. however, take my words with a grain of salt; i'm sure the maintainers know a lot better

I really appreciate you guys putting effort into this library, thank you!

2022-05-09 09:39 UTC, closed without merging